.Dd January 19, 2020
.Dt RAT-RECORD 1
.Os

.Sh NAME
.Nm rat-record
.Nd Invoke arecord so that it works for ratox

.Sh SYNOPSIS
.Nm

.Sh DESCRIPTION
.Nm
is a shortcut that plays its standard input, configured for the typical
ratox output (rate of 48 kHz, fromat of S16_LE).

.Sh EXIT STATUS
.Ex -std

.Sh SEE ALSO
.Xr rat-play 1 ,
.Xr ratox 1 .

.Sh AUTHORS
.An pranomostro Aq Mt pranomostro@posteo.net
