#!/bin/sh
# Remote microphone script
# Usage:
#    rat-remotemic
#        If no call is pending it'll initiate the call, if call is pending, it'll be answered
#        It should be called within friend dir, where call_in and call_out pipes reside

LIBRARY_LOCATION=`dirname $BASH_SOURCE`
. $LIBRARY_LOCATION/functions
export PATH=$LIBRARY_LOCATION:$PATH

function remotemic() {
    TRASHER=$(stdin_trasher)
    arecord -r 48000 -c 1 -f S16_LE -
}

test "X$(basename -- "$0")" = "Xrat-remotemic" && remotemic < call_out > call_in
