.Dd January 10, 2020
.Dt RAT-PLAY 1
.Os

.Sh NAME
.Nm rat-play
.Nd Invoke aplay so that it works for ratox

.Sh SYNOPSIS
.Nm

.Sh DESCRIPTION
.Nm
is a shortcut that plays its standard input, configured for the typical
ratox output (rate of 48 kHz, fromat of S16_LE).

.Sh EXIT STATUS
.Ex -std

.Sh SEE ALSO
.Xr rat-record 1 ,
.Xr ratox 1 .

.Sh AUTHORS
.An pranomostro Aq Mt pranomostro@posteo.net
