.Dd December 27, 2019
.Dt RAT-AUTOAPPROVE 1
.Os

.Sh NAME
.Nm rat-autoapprove
.Nd Automatically approve every incoming friend request

.Sh SYNOPSIS
.Nm

.Sh DESCRIPTION
.Nm
should be called in a directory with a running
.Xr ratox 1
instance. It monitors the request/out/ directory for incoming friend
requests, and automatically approves them when they occur.

.Sh EXIT STATUS
.Ex -std

.Sh SEE ALSO
.Xr ratox 1 .

.Sh AUTHORS
.An pranomostro Aq Mt pranomostro@posteo.net
